---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cc-pc-room.kr
  resources:
  - jeonjiks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cc-pc-room.kr
  resources:
  - jeonjiks/finalizers
  verbs:
  - update
- apiGroups:
  - cc-pc-room.kr
  resources:
  - jeonjiks/status
  verbs:
  - get
  - patch
  - update
