//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CleanupPolicy) DeepCopyInto(out *CleanupPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CleanupPolicy.
func (in *CleanupPolicy) DeepCopy() *CleanupPolicy {
	if in == nil {
		return nil
	}
	out := new(CleanupPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CleanupPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CleanupPolicyList) DeepCopyInto(out *CleanupPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CleanupPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CleanupPolicyList.
func (in *CleanupPolicyList) DeepCopy() *CleanupPolicyList {
	if in == nil {
		return nil
	}
	out := new(CleanupPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CleanupPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CleanupPolicySpec) DeepCopyInto(out *CleanupPolicySpec) {
	*out = *in
	if in.IncludeNamespaces != nil {
		in, out := &in.IncludeNamespaces, &out.IncludeNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeNamspaces != nil {
		in, out := &in.ExcludeNamspaces, &out.ExcludeNamspaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PodPolicies != nil {
		in, out := &in.PodPolicies, &out.PodPolicies
		*out = new(PodCleanupPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.PVPolicies != nil {
		in, out := &in.PVPolicies, &out.PVPolicies
		*out = new(PVCleanupPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CleanupPolicySpec.
func (in *CleanupPolicySpec) DeepCopy() *CleanupPolicySpec {
	if in == nil {
		return nil
	}
	out := new(CleanupPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CleanupPolicyStatus) DeepCopyInto(out *CleanupPolicyStatus) {
	*out = *in
	if in.LastExecutionTime != nil {
		in, out := &in.LastExecutionTime, &out.LastExecutionTime
		*out = (*in).DeepCopy()
	}
	if in.NextExecutionTime != nil {
		in, out := &in.NextExecutionTime, &out.NextExecutionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PendingApproval != nil {
		in, out := &in.PendingApproval, &out.PendingApproval
		*out = make([]PendingResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CleanupPolicyStatus.
func (in *CleanupPolicyStatus) DeepCopy() *CleanupPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(CleanupPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailedPodPolicy) DeepCopyInto(out *FailedPodPolicy) {
	*out = *in
	if in.States != nil {
		in, out := &in.States, &out.States
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailedPodPolicy.
func (in *FailedPodPolicy) DeepCopy() *FailedPodPolicy {
	if in == nil {
		return nil
	}
	out := new(FailedPodPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdlePodPolicy) DeepCopyInto(out *IdlePodPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdlePodPolicy.
func (in *IdlePodPolicy) DeepCopy() *IdlePodPolicy {
	if in == nil {
		return nil
	}
	out := new(IdlePodPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCleanupPolicy) DeepCopyInto(out *PVCleanupPolicy) {
	*out = *in
	if in.States != nil {
		in, out := &in.States, &out.States
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCleanupPolicy.
func (in *PVCleanupPolicy) DeepCopy() *PVCleanupPolicy {
	if in == nil {
		return nil
	}
	out := new(PVCleanupPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingResource) DeepCopyInto(out *PendingResource) {
	*out = *in
	in.MarkedAt.DeepCopyInto(&out.MarkedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingResource.
func (in *PendingResource) DeepCopy() *PendingResource {
	if in == nil {
		return nil
	}
	out := new(PendingResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCleanupPolicy) DeepCopyInto(out *PodCleanupPolicy) {
	*out = *in
	if in.FailePods != nil {
		in, out := &in.FailePods, &out.FailePods
		*out = new(FailedPodPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.IdlePods != nil {
		in, out := &in.IdlePods, &out.IdlePods
		*out = new(IdlePodPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCleanupPolicy.
func (in *PodCleanupPolicy) DeepCopy() *PodCleanupPolicy {
	if in == nil {
		return nil
	}
	out := new(PodCleanupPolicy)
	in.DeepCopyInto(out)
	return out
}
